auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: "127.0.0.1"
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_chunk_age: 1h

schema_config:
  configs:
    - from: "2025-02-19"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: "C:\\Observability\\loki\\tsdb-index"
    cache_location: "C:\\Observability\\loki\\tsdb-cache"
  filesystem:
    directory: "C:\\Observability\\loki\\chunks"

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: true

compactor:
  working_directory: "C:\\Observability\\loki\\compactor"

common:
  path_prefix: "C:\\Observability\\loki"